### ISSUE TITLE
scls19fr/GPX.jl

### ISSUE THREAD

**Issue by scls19fr** [alhirzel/GPX.jl#1]
Hi @alhirzel,

you might be interested by https://github.com/scls19fr/GPX.jl
but it's still a WIP.

Kind regards

**Comment by alhirzel** [comment]
Looks more mature than mine! I will default to yours in the future, thanks for the heads-up!

**Comment by alhirzel** [comment]
depreciated by 99185f101f5525b138ee8305b98e2c4a3b608a4e
